export const DELIVERY_PARTNERS = {
    DELIVERY_PARTNERS_START: "DELIVERY_PARTNERS_START",
    DELIVERY_PARTNERS_SUCCESS:"DELIVERY_PARTNERS_SUCCESS", 
    DELIVERY_PARTNERS_FAIL: "DELIVERY_PARTNERS_FAIL"
}